// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_S8U7WVg0LDuyodPNbTBEEuhkuWJs3nQ',
    appId: '1:468766802785:android:cbc2a62dd2fd1af6c73b20',
    messagingSenderId: '468766802785',
    projectId: 'newproject-1a3c7',
    databaseURL: 'https://newproject-1a3c7.firebaseio.com',
    storageBucket: 'newproject-1a3c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdRsQegcSbaN3uS8VrN8_MnnJ88warBLA',
    appId: '1:468766802785:ios:d297c700e0c7da42c73b20',
    messagingSenderId: '468766802785',
    projectId: 'newproject-1a3c7',
    databaseURL: 'https://newproject-1a3c7.firebaseio.com',
    storageBucket: 'newproject-1a3c7.appspot.com',
    iosClientId: '468766802785-to4dpd4fcm1tbocnno59osgc2q4ap21n.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsUpGenix',
  );
}
